### ISSUE TITLE
I can't seem to get this to work.

### ISSUE THREAD

**Issue by spaelectronics** [jneilliii/OctoPrint-SmoothiewareConfig#1]
Everytime I try to upload config.txt using the "Upload to SD" button, it says "Saving..." and just sits there forever. 
Nothing displays in the terminal log either.

**Comment by jneilliii** [comment]
Yeah, I was afraid of that.  All my testing was with local storage and when I tried with SD it did the same. I'm not really sure why. I assume it's something to do with how foosel is doing the transfer from local to SD.  I'll see if she has any recommendations.

**Comment by foosel** [comment]
Replying here since this seems like it's the reason of your comment foosel/OctoPrint#1652.

I can't really say much without seeing an example `serial.log` and an `octoprint.log` of the issue you are running into. In general you should be able to do "dry runs" against the [virtual printer](http://docs.octoprint.org/en/maintenance/development/virtual_printer.html) to test this. The extension tree first and foremost allows uploading the file. I could imagine that somewhere in the processing of the file transfer there is still something that expects a gcode file and that gets confused when it doesn't get something ending on this extension. So this might be something that needs an adjustment in OctoPrint after all.

**Comment by jneilliii** [comment]
Yeah, I just tested with the virtual printer and what appears to be happening is probably by design.  I used the extension tree defining these filetypes as models thinking binary files would potentially need to be used to transfer bin files to sd card for firmware updates, but it looks like octoprint doesn't transfer those types by default.  Going to test switching the txt type to machinecode and see if that works for transferring.

**Comment by jneilliii** [comment]
Switching txt files to machinecode made no difference in the file transferring to SD card.  What happens is the file uploads locally and the progress never changes to Streaming, as it does with gcode files and never seems to start the transfer process at all, progress gets stuck on Saving.  Here are the octoprint.log and serial.log.

[octoprint.log](https://github.com/jneilliii/OctoPrint-SmoothiewareConfig/files/1447772/octoprint.log)
[serial.log](https://github.com/jneilliii/OctoPrint-SmoothiewareConfig/files/1447773/serial.log)

**Comment by foosel** [comment]
Yeah, that's something I'll need to take a look at in OctoPrint. Might be a while though and even necessitate changes that are not a fast fix.

**Comment by foosel** [comment]
I just pushed two commits (see above) that address this on OctoPrint's side. They are available on `maintenance`, soon `devel` and will be part of the 1.3.6 release.

Streaming a `txt` file (registered as `machinecode`, sub type whatever you want) works that way, but with limitations. To quote myself from one of the commit messages:

> No guarantees however that transporting anything BUT gcode via the usual
> M28/M29 interface will even remotely work. Note that it most likely
> won't work if the transferred file contains an M29 (= end transfer),
> just like with transferred GCODE files.
> 
> Also note that stuff like config files or some such that might be
> transferred might contain lines that are too large to fit into the
> buffer of the printer. This is really just to enable plugins to maybe do
> some nifty stuff, no official support of streaming arbitrary files to
> the printer's SD (for that we'd need WAY more firmware support first).

I don't know if transferring a Smoothieware config through the SD streaming functionality will even produce the desired results with regards to updating the config file or not, but at least it will now work from OctoPrint's side.
